##########################################################
##################  所有profile共有的配置  #################
##########################################################


###################  spring配置  ###################
spring:
  profiles:
    active: dev
  http:
    multipart:
      max-request-size: 500MB #最大请求大小
      max-file-size: 500MB #最大文件大小
  devtools:
    restart:
      additional-paths: src/main/java
#  aop:
#    proxy-target-class: true #false为启用jdk默认动态代理,true为cglib动态代理

###################  swagger配置  ###################
swagger:
  enabled: true
  title: 笔芯
  description: 笔芯APP接口
  version: 0.1
  contact:
    name: mifan and CJ
    url: https://qqabcv520.github.io/mifanBlog/build
    email: 605655316@qq.com
  base-package: cn.mifan123.refill
  termsOfServiceUrl: https://github.com/qqabcv520/refill-api

common.jwt-key: bWlmYW4=



---

##########################################################
###################  开发环境的profile  ###################
##########################################################
spring:
  profiles: dev
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
#    url: jdbc:mysql://103.228.131.139:3306/refill?autoReconnect=true&useUnicode=true&characterEncoding=utf8
#    username: Refill
#    password: ca2sNnhSjLuJ293vaG4sd30nh
    url: jdbc:mysql://127.0.0.1:3306/refill?autoReconnect=true&useUnicode=true&characterEncoding=utf8
    username: root
    password: root



logging:
  level.root: info
#  level.cn.rocketspeed: debug
  path: logs/
  file: refill.log

server:
  port: 80

#---
#
###########################################################
####################  正式环境的profile  ###################
###########################################################
#spring:
#  profiles: produce
#  datasource:
#    url: jdbc:mysql://119.29.142.108:3306/haocheng?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull
#    username: haocheng
#    password: haochengAdmin