##########################################################
##################  所有profile共有的配置  #################
##########################################################


###################  spring配置  ###################
spring:
  profiles:
    active: dev
  jpa:
    hibernate:
      ddl-auto: update
  http:
    multipart:
      max-request-size: 500MB #最大请求大小
      max-file-size: 500MB #最大文件大小
  devtools:
    restart:
      additional-paths: src/main/java
#  aop:
#    proxy-target-class: true #false为启用jdk默认动态代理,true为cglib动态代理

###################  swagger配置  ###################
swagger:
  enabled: true
  title: 笔芯
  description: 笔芯APP接口
  version: 0.1
  contact:
    name: mifan and CJ
    url: https://qqabcv520.github.io/mifanBlog/build
    email: 605655316@qq.com
  base-package: cn.mifan123.refill
  termsOfServiceUrl: https://github.com/qqabcv520/refill-api

common:
  jwt-key: bWlmYW4=
  jwt-expiration: 1296000000
  j-message-app-key: 91ec783f87a0fb9db61da80f
  j-message-secret: d6ecf7f4b1f5d9a039addaf7



---

##########################################################
###################  开发环境的profile  ###################
##########################################################
spring:
  profiles: dev
  jpa:
    show-sql: true
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/refill?autoReconnect=true&useUnicode=true&characterEncoding=utf8
    username: root
    password: root
#    url: jdbc:mysql://114.67.133.63:3306/refill?autoReconnect=true&useUnicode=true&characterEncoding=utf8
#    username: refill
#    password: hQD4KtL6WvDpxM4E



logging:
  level.root: info
#  level.cn.rocketspeed: debug
  path: ./logs/
  file: refill.log

server:
  port: 80

---

##########################################################
###################  正式环境的profile  ###################
##########################################################
spring:
  profiles: produce
  datasource:
    url: jdbc:mysql://114.67.133.63:3306/refill?autoReconnect=true&useUnicode=true&characterEncoding=utf8
    username: refill
    password: hQD4KtL6WvDpxM4E
server:
  port: 8081

logging:
  level.root: warn
  path: ./logs/
  file: refill.log